package com.banking.handoff.integration;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.File;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.UUID;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.batch.core.BatchStatus;
import org.springframework.batch.core.Job;
import org.springframework.batch.core.JobExecution;
import org.springframework.batch.core.JobParameters;
import org.springframework.batch.core.JobParametersBuilder;
import org.springframework.batch.core.launch.support.TaskExecutorJobLauncher;
import org.springframework.batch.core.repository.JobRepository;
import org.springframework.batch.test.JobLauncherTestUtils;
import org.springframework.batch.test.JobRepositoryTestUtils;
import org.springframework.batch.test.context.SpringBatchTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;

@SpringBatchTest
@SpringBootTest
@ActiveProfiles("test")
class HandoffJobIntegrationTest {

    @Autowired private JobLauncherTestUtils jobLauncherTestUtils;
    @Autowired private JobRepositoryTestUtils jobRepositoryTestUtils;
    @Autowired private JdbcTemplate jdbcTemplate;
    @Autowired private JobRepository jobRepository;

    @Autowired @Qualifier("populationJob")      private Job populationJob;
    @Autowired @Qualifier("instrumentFeedJob")  private Job instrumentFeedJob;
    @Autowired @Qualifier("accountingFeedJob")  private Job accountingFeedJob;

    private String tempOutputDir;
    private TaskExecutorJobLauncher syncLauncher;

    @BeforeEach
    void setUp() throws Exception {
        syncLauncher = new TaskExecutorJobLauncher();
        syncLauncher.setJobRepository(jobRepository);
        syncLauncher.afterPropertiesSet();
        jobLauncherTestUtils.setJobLauncher(syncLauncher);
        jobRepositoryTestUtils.removeJobExecutions();

        tempOutputDir = System.getProperty("java.io.tmpdir") + "/handoff-test";
        new File(tempOutputDir).mkdirs();

        // Source tables
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS test_instrument_header (
                    instrument_id          VARCHAR(20) NOT NULL,
                    collection_number      VARCHAR(20),
                    business_date          VARCHAR(10),
                    draw_reference_number  VARCHAR(30),
                    instrument_amount      DECIMAL(15,2),
                    bank_code              VARCHAR(10),
                    instrument_status      VARCHAR(20),
                    PRIMARY KEY (instrument_id)
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS test_accounting_entry (
                    instrument_number  VARCHAR(20) NOT NULL,
                    collection_number  VARCHAR(20),
                    accounting_status  VARCHAR(20),
                    debit_amount       DECIMAL(15,2),
                    credit_amount      DECIMAL(15,2),
                    bank_code          VARCHAR(10),
                    value_date         VARCHAR(10),
                    entry_status       VARCHAR(20),
                    PRIMARY KEY (instrument_number)
                )
                """);

        // Staging tables (BIGINT GENERATED BY DEFAULT AS IDENTITY for H2 compat)
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS test_instrument_header_staging (
                    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    batch_run_id           VARCHAR(36) NOT NULL,
                    instrument_id          VARCHAR(20),
                    collection_number      VARCHAR(20),
                    business_date          VARCHAR(10),
                    draw_reference_number  VARCHAR(30),
                    instrument_amount      DECIMAL(15,2),
                    bank_code              VARCHAR(10)
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS test_accounting_staging (
                    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    batch_run_id       VARCHAR(36) NOT NULL,
                    instrument_number  VARCHAR(20),
                    collection_number  VARCHAR(20),
                    accounting_status  VARCHAR(20),
                    debit_amount       DECIMAL(15,2),
                    credit_amount      DECIMAL(15,2),
                    bank_code          VARCHAR(10),
                    value_date         VARCHAR(10)
                )
                """);

        // Feed query config table — queries point at H2 test staging tables
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS feed_query_config (
                    feed_name      VARCHAR(50) NOT NULL,
                    select_clause  VARCHAR(500) NOT NULL,
                    from_clause    VARCHAR(200) NOT NULL,
                    where_clause   VARCHAR(200),
                    sort_key       VARCHAR(50) NOT NULL,
                    PRIMARY KEY (feed_name)
                )
                """);

        jdbcTemplate.execute("DELETE FROM test_instrument_header_staging");
        jdbcTemplate.execute("DELETE FROM test_accounting_staging");
        jdbcTemplate.execute("DELETE FROM test_instrument_header");
        jdbcTemplate.execute("DELETE FROM test_accounting_entry");
        jdbcTemplate.execute("DELETE FROM feed_query_config");

        jdbcTemplate.update("""
                INSERT INTO feed_query_config (feed_name, select_clause, from_clause, where_clause, sort_key)
                VALUES (?, ?, ?, ?, ?)
                """,
                "INSTRUMENT_FEED",
                "instrument_id, collection_number, business_date, draw_reference_number, instrument_amount, bank_code",
                "test_instrument_header_staging",
                "batch_run_id = :batchRunId",
                "instrument_id");

        jdbcTemplate.update("""
                INSERT INTO feed_query_config (feed_name, select_clause, from_clause, where_clause, sort_key)
                VALUES (?, ?, ?, ?, ?)
                """,
                "ACCOUNTING_FEED",
                "instrument_number, collection_number, accounting_status, debit_amount, credit_amount, bank_code, value_date",
                "test_accounting_staging",
                "batch_run_id = :batchRunId",
                "instrument_number");
    }

    @AfterEach
    void tearDown() {
        jobRepositoryTestUtils.removeJobExecutions();
    }

    @Test
    void populationJobShouldPopulateBothStagingTables() throws Exception {
        insertInstrumentHeader("INSTR-001", "COL-001", "2026-05-09", "DRAW-001", new BigDecimal("15000.00"), "BANKX");
        insertAccountingEntry("INSTR-001", "COL-001", "PAID", new BigDecimal("15000.00"), BigDecimal.ZERO, "BANKX", "2026-05-09");

        String batchRunId = UUID.randomUUID().toString();
        jobLauncherTestUtils.setJob(populationJob);
        JobExecution execution = jobLauncherTestUtils.launchJob(populationParams(batchRunId));

        assertThat(execution.getStatus()).isEqualTo(BatchStatus.COMPLETED);

        int instrCount = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM test_instrument_header_staging WHERE batch_run_id = ?",
                Integer.class, batchRunId);
        int acctCount = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM test_accounting_staging WHERE batch_run_id = ?",
                Integer.class, batchRunId);

        assertThat(instrCount).isEqualTo(1);
        assertThat(acctCount).isEqualTo(1);
    }

    @Test
    void instrumentFeedJobShouldWriteFixedWidthFile() throws Exception {
        String batchRunId = UUID.randomUUID().toString();
        insertInstrumentStaging(batchRunId, "INSTR-001", "COL-001", "2026-05-09", "DRAW-001", new BigDecimal("15000.00"), "BANKX");
        insertInstrumentStaging(batchRunId, "INSTR-002", "COL-002", "2026-05-09", "DRAW-002", new BigDecimal("25000.50"), "BANKY");

        String outputFile = tempOutputDir + "/TEST_INSTRUMENT_INTEGRATION.dat";
        jobLauncherTestUtils.setJob(instrumentFeedJob);
        JobExecution execution = jobLauncherTestUtils.launchJob(feedParams(batchRunId, outputFile));

        assertThat(execution.getStatus()).isEqualTo(BatchStatus.COMPLETED);
        assertThat(new File(outputFile)).exists();

        List<String> lines = Files.readAllLines(Path.of(outputFile));
        assertThat(lines).hasSize(2);
        // 20 + 20 + 10 + 30 + 15 + 10 = 105 chars per fixed-width line
        assertThat(lines.get(0)).hasSize(105);
        assertThat(lines.get(0).substring(0, 20).stripTrailing()).isEqualTo("INSTR-001");
        // instrument_amount is right-padded with zeros: 000000015000.00
        assertThat(lines.get(0).substring(80, 95)).isEqualTo("000000015000.00");
    }

    @Test
    void accountingFeedJobShouldWriteCsvFile() throws Exception {
        String batchRunId = UUID.randomUUID().toString();
        insertAccountingStaging(batchRunId, "INSTR-001", "COL-001", "PAID",
                new BigDecimal("15000.00"), BigDecimal.ZERO, "BANKX", "2026-05-09");

        String outputFile = tempOutputDir + "/TEST_ACCOUNTING_INTEGRATION.csv";
        jobLauncherTestUtils.setJob(accountingFeedJob);
        JobExecution execution = jobLauncherTestUtils.launchJob(feedParams(batchRunId, outputFile));

        assertThat(execution.getStatus()).isEqualTo(BatchStatus.COMPLETED);

        List<String> lines = Files.readAllLines(Path.of(outputFile));
        assertThat(lines).hasSize(1);
        // CSV: 7 comma-separated padded fields
        String[] fields = lines.get(0).split(",");
        assertThat(fields).hasSize(7);
        assertThat(fields[0].stripTrailing()).isEqualTo("INSTR-001");
        assertThat(fields[2].stripTrailing()).isEqualTo("PAID");
    }

    @Test
    void populationJobShouldIsolateRunsByBatchRunId() throws Exception {
        insertInstrumentHeader("INSTR-001", "COL-001", "2026-05-09", "DRAW-001", new BigDecimal("10000.00"), "BANKX");

        String batchRunId1 = UUID.randomUUID().toString();
        String batchRunId2 = UUID.randomUUID().toString();

        jobLauncherTestUtils.setJob(populationJob);
        syncLauncher.run(populationJob, populationParams(batchRunId1));
        syncLauncher.run(populationJob, populationParams(batchRunId2));

        int count1 = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM test_instrument_header_staging WHERE batch_run_id = ?",
                Integer.class, batchRunId1);
        int count2 = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM test_instrument_header_staging WHERE batch_run_id = ?",
                Integer.class, batchRunId2);

        assertThat(count1).isEqualTo(1);
        assertThat(count2).isEqualTo(1);
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private void insertInstrumentHeader(String instrId, String collNo, String bizDate,
            String drawRef, BigDecimal amount, String bankCode) {
        jdbcTemplate.update("""
                INSERT INTO test_instrument_header
                (instrument_id, collection_number, business_date, draw_reference_number,
                 instrument_amount, bank_code, instrument_status)
                VALUES (?, ?, ?, ?, ?, ?, 'ACTIVE')
                """, instrId, collNo, bizDate, drawRef, amount, bankCode);
    }

    private void insertAccountingEntry(String instrNo, String collNo, String status,
            BigDecimal debit, BigDecimal credit, String bankCode, String valueDate) {
        jdbcTemplate.update("""
                INSERT INTO test_accounting_entry
                (instrument_number, collection_number, accounting_status,
                 debit_amount, credit_amount, bank_code, value_date, entry_status)
                VALUES (?, ?, ?, ?, ?, ?, ?, 'PENDING')
                """, instrNo, collNo, status, debit, credit, bankCode, valueDate);
    }

    private void insertInstrumentStaging(String batchRunId, String instrId, String collNo,
            String bizDate, String drawRef, BigDecimal amount, String bankCode) {
        jdbcTemplate.update("""
                INSERT INTO test_instrument_header_staging
                (batch_run_id, instrument_id, collection_number, business_date,
                 draw_reference_number, instrument_amount, bank_code)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """, batchRunId, instrId, collNo, bizDate, drawRef, amount, bankCode);
    }

    private void insertAccountingStaging(String batchRunId, String instrNo, String collNo,
            String status, BigDecimal debit, BigDecimal credit, String bankCode, String valueDate) {
        jdbcTemplate.update("""
                INSERT INTO test_accounting_staging
                (batch_run_id, instrument_number, collection_number, accounting_status,
                 debit_amount, credit_amount, bank_code, value_date)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """, batchRunId, instrNo, collNo, status, debit, credit, bankCode, valueDate);
    }

    private JobParameters populationParams(String batchRunId) {
        return new JobParametersBuilder()
                .addString("batchRunId", batchRunId)
                .addLong("run.id", System.currentTimeMillis())
                .toJobParameters();
    }

    private JobParameters feedParams(String batchRunId, String outputFilePath) {
        return new JobParametersBuilder()
                .addString("batchRunId", batchRunId)
                .addString("outputFilePath", outputFilePath)
                .addLong("run.id", System.currentTimeMillis())
                .toJobParameters();
    }
}
