package com.banking.handoff.integration;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.UUID;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.batch.core.BatchStatus;
import org.springframework.batch.core.Job;
import org.springframework.batch.core.JobExecution;
import org.springframework.batch.core.JobParameters;
import org.springframework.batch.core.JobParametersBuilder;
import org.springframework.batch.core.launch.support.TaskExecutorJobLauncher;
import org.springframework.batch.core.repository.JobRepository;
import org.springframework.batch.test.JobLauncherTestUtils;
import org.springframework.batch.test.JobRepositoryTestUtils;
import org.springframework.batch.test.context.SpringBatchTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;

@SpringBatchTest
@SpringBootTest
@ActiveProfiles("test")
class HandoffJobIntegrationTest {

    @Autowired
    private JobLauncherTestUtils jobLauncherTestUtils;

    @Autowired
    private JobRepositoryTestUtils jobRepositoryTestUtils;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    @Qualifier("stagingJob")
    private Job stagingJob;

    @Autowired
    @Qualifier("instrumentFeedJob")
    private Job instrumentFeedJob;

    @Autowired
    @Qualifier("accountingFeedJob")
    private Job accountingFeedJob;

    @Autowired
    private JobRepository jobRepository;

    private String tempOutputDir;
    private TaskExecutorJobLauncher syncLauncher;

    @BeforeEach
    void setUp() throws Exception {
        syncLauncher = new TaskExecutorJobLauncher();
        syncLauncher.setJobRepository(jobRepository);
        syncLauncher.afterPropertiesSet();

        jobLauncherTestUtils.setJobLauncher(syncLauncher);

        jobRepositoryTestUtils.removeJobExecutions();

        tempOutputDir = System.getProperty("java.io.tmpdir") + "/handoff-test";
        new File(tempOutputDir).mkdirs();

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS test_accounts (
                    account_no VARCHAR(20) NOT NULL,
                    customer_name VARCHAR(100),
                    balance DECIMAL(15,2),
                    status VARCHAR(10),
                    record_type VARCHAR(20),
                    PRIMARY KEY (account_no)
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS test_handoff_staging (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    batch_run_id VARCHAR(36) NOT NULL,
                    account_no VARCHAR(20),
                    customer_name VARCHAR(100),
                    balance DECIMAL(15,2),
                    record_type VARCHAR(20)
                )
                """);

        jdbcTemplate.execute("DELETE FROM test_handoff_staging");
        jdbcTemplate.execute("DELETE FROM test_accounts");
    }

    @AfterEach
    void tearDown() {
        jobRepositoryTestUtils.removeJobExecutions();
    }

    @Test
    void stagingJobShouldPopulateStagingTable() throws Exception {
        insertSourceAccount("ACC00000000000000001", "John Smith", 1234.56, "INSTRUMENT");
        insertSourceAccount("ACC00000000000000002", "Jane Doe", 5678.90, "ACCOUNTING");

        String batchRunId = UUID.randomUUID().toString();
        JobParameters params = stagingParams(batchRunId);

        jobLauncherTestUtils.setJob(stagingJob);
        JobExecution execution = jobLauncherTestUtils.launchJob(params);

        assertThat(execution.getStatus()).isEqualTo(BatchStatus.COMPLETED);

        int count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM test_handoff_staging WHERE batch_run_id = ?",
                Integer.class, batchRunId);
        assertThat(count).isEqualTo(2);
    }

    @Test
    void instrumentFeedJobShouldWriteFixedWidthFile() throws Exception {
        String batchRunId = UUID.randomUUID().toString();
        insertStagingRow(batchRunId, "ACC00000000000000001", "John Smith", 1234.56, "INSTRUMENT");
        insertStagingRow(batchRunId, "ACC00000000000000002", "Jane Doe", 5678.90, "INSTRUMENT");

        String outputFile = tempOutputDir + "/TEST_INSTRUMENT_INTEGRATION.dat";
        JobParameters params = feedParams(batchRunId, outputFile);

        jobLauncherTestUtils.setJob(instrumentFeedJob);
        JobExecution execution = jobLauncherTestUtils.launchJob(params);

        assertThat(execution.getStatus()).isEqualTo(BatchStatus.COMPLETED);
        assertThat(new File(outputFile)).exists();

        List<String> lines = Files.readAllLines(Path.of(outputFile));
        assertThat(lines).hasSize(2);
        assertThat(lines.get(0)).hasSize(75); // 20 + 40 + 15
        assertThat(lines.get(0).substring(0, 20).stripTrailing()).isEqualTo("ACC00000000000000001");
    }

    @Test
    void accountingFeedJobShouldWriteFixedWidthFile() throws Exception {
        String batchRunId = UUID.randomUUID().toString();
        insertStagingRow(batchRunId, "ACC00000000000000001", "Alice Brown", 9999.99, "ACCOUNTING");

        String outputFile = tempOutputDir + "/TEST_ACCOUNTING_INTEGRATION.dat";
        JobParameters params = feedParams(batchRunId, outputFile);

        jobLauncherTestUtils.setJob(accountingFeedJob);
        JobExecution execution = jobLauncherTestUtils.launchJob(params);

        assertThat(execution.getStatus()).isEqualTo(BatchStatus.COMPLETED);

        List<String> lines = Files.readAllLines(Path.of(outputFile));
        assertThat(lines).hasSize(1);
        assertThat(lines.get(0)).hasSize(75);

        String balance = lines.get(0).substring(60, 75);
        assertThat(balance).isEqualTo("000000009999.99");
    }

    @Test
    void stagingJobShouldIsolateRunsByBatchRunId() throws Exception {
        insertSourceAccount("ACC00000000000000001", "John Smith", 1234.56, "INSTRUMENT");

        String batchRunId1 = UUID.randomUUID().toString();
        String batchRunId2 = UUID.randomUUID().toString();

        jobLauncherTestUtils.setJob(stagingJob);

        JobExecution exec1 = syncLauncher.run(stagingJob, stagingParams(batchRunId1));
        JobExecution exec2 = syncLauncher.run(stagingJob, stagingParams(batchRunId2));

        assertThat(exec1.getStatus()).isEqualTo(BatchStatus.COMPLETED);
        assertThat(exec2.getStatus()).isEqualTo(BatchStatus.COMPLETED);

        int count1 = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM test_handoff_staging WHERE batch_run_id = ?",
                Integer.class, batchRunId1);
        int count2 = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM test_handoff_staging WHERE batch_run_id = ?",
                Integer.class, batchRunId2);
        assertThat(count1).isEqualTo(1);
        assertThat(count2).isEqualTo(1);
    }

    private void insertSourceAccount(String accNo, String name, double balance, String recordType) {
        jdbcTemplate.update(
                "INSERT INTO test_accounts (account_no, customer_name, balance, status, record_type) VALUES (?, ?, ?, ?, ?)",
                accNo, name, balance, "ACTIVE", recordType);
    }

    private void insertStagingRow(String batchRunId, String accNo, String name, double balance, String recordType) {
        jdbcTemplate.update(
                "INSERT INTO test_handoff_staging (batch_run_id, account_no, customer_name, balance, record_type) VALUES (?, ?, ?, ?, ?)",
                batchRunId, accNo, name, balance, recordType);
    }

    private JobParameters stagingParams(String batchRunId) {
        return new JobParametersBuilder()
                .addString("batchRunId", batchRunId)
                .addLong("run.id", System.currentTimeMillis())
                .toJobParameters();
    }

    private JobParameters feedParams(String batchRunId, String outputFilePath) {
        return new JobParametersBuilder()
                .addString("batchRunId", batchRunId)
                .addString("outputFilePath", outputFilePath)
                .addLong("run.id", System.currentTimeMillis())
                .toJobParameters();
    }
}
